#! /bin/bash

ids=()
# filter to tiled windows
for id in "$@"; do
    if [ -n "$id" ]; then
        # can't filter by .tiled if querying by $id, so use focus
        [ "$(bspc query -W -w focused)" != "$id" ] && focus=y
        [ -n "$focus" ] && bspc window -f "$id"
        [ -n "$(bspc query -W -w focused.tiled)" ] && ids+=("$id")
        [ -n "$focus" ] && bspc window -f last
    fi
done

# only do something if there's more than one tiled window
if [ -n "$(bspc query -W -w last.tiled)" ]; then
    # make all new windows floating
    for id in "${ids[@]}"; do
        bspc window "$id" -t floating
    done
    
    # place each window in turn by transplanting into the biggest window
    for id in "${ids[@]}"; do
        "$BSPWM_SCRIPTS_DIR/auto-presel" br biggest
        dest_id="$(bspc query -W -w biggest)"
        bspc window "$id" -t floating
        bspc window "$id" -w "$dest_id"
    done
fi
