#! /bin/bash

# only do something if there's already a tiled window on this desktop
if [ -n "$(bspc query -N -n biggest.tiled)" ]; then
    if [ -n "$(bspc query -N -n biggest.tiled.\!automatic)" ]; then
        # we have a presel: use it by choosing the 'target' window
        echo node=biggest.tiled.\!automatic
    else
        # no presel exists: transplant into the biggest window
        dir="$("$BSPWM_SCRIPTS_DIR/get-auto-presel" br biggest.tiled)"
        echo node=biggest.tiled split_dir="$dir"
    fi
fi
