#! /bin/bash

dir="${1:br}"
target="${2:-focused}"

orientation="$("$BSPWM_SCRIPTS_DIR"/get-window-alignment "$target")"
if [ "$orientation" = vertical ]; then
    [ "$dir" = tl ] && d=up || d=down
else
    [ "$dir" = tl ] && d=left || d=right
fi
bspc window "$target" -p "$d"
