#! /bin/bash

dir="${1:br}"
target="${2:-focused}"

orientation="$("$BSPWM_SCRIPTS_DIR"/get-window-alignment "$target")"
if [ "$orientation" = vertical ]; then
    [ "$dir" = tl ] && echo up || echo down
else
    [ "$dir" = tl ] && echo left || echo right
fi
