#! /bin/bash

dir="${1:br}"
target="${2:-focused}"

orientation="$("$BSPWM_SCRIPTS_DIR"/get-window-alignment "$target")"
if [ "$orientation" = vertical ]; then
    [ "$dir" = tl ] && echo north || echo south
else
    [ "$dir" = tl ] && echo west || echo east
fi
