#! /bin/bash

dir="$("$BSPWM_SCRIPTS_DIR"/get-nearest-edge "$(bspc query -W -w focused)")"
if [ -n "$dir" ]; then
    if [ "$dir" = right ] || [ "$dir" = left ]; then
        angle=90
    else
        angle=-90
    fi
    echo $dir $angle
    bspc window -R "$dir" "$angle"
fi
