#! /bin/bash

alias pac='pacman'
alias pacman='pacman --color=auto'
alias paclog='less -R /var/log/pacman.log'
alias inst='sudo pacman -S'
alias uninst='sudo pacman -Rs'
alias up='sudo pacman -Syu'
alias pactree='pactree -c'
alias pacnew='pacsave'

aur-sync-git () {
    aur-sync -f $(pacman -Qm | while read line; do
        pkg=($line)
        if echo ${pkg[1]} | grep -Eq '^[[:digit:]]{8}-[[:digit:]]+$' \
           || echo ${pkg[0]} | grep -q -- '-git$' \
           || echo ${pkg[0]} | grep -q -- '-hg$' \
           || echo ${pkg[0]} | grep -q -- '-bzr$'; then
            echo ${pkg[0]}
        fi
    done)
}
