#! /bin/bash

gap=2
bspc config border_width 2
bspc config window_gap $gap
for border in left top right; do
    bspc config ${border}_padding -$gap
done
bspc config bottom_padding $((22-gap))

bspc config focused_border_color '#ff9a00'
bspc config normal_border_color '#563f64'

bspc config auto_cancel true

# set up desktops - need to do this after some settings above, since they're
# global and get applied to desktops when they're created/reset
"$BSPWM_SCRIPTS_DIR"/desktop-wall init
