#! /bin/bash

# appearance

gap=2
bspc config border_width 2
bspc config window_gap $gap
for border in left top right; do
    bspc config ${border}_padding -$gap
done
bspc config bottom_padding $((21-gap))

bspc config normal_border_color '#563f64'
bspc config active_border_color '#563f64'
bspc config focused_border_color '#ff9a00'
bspc config presel_feedback_color '#ff9a00'

# input

bspc config pointer_modifier mod1
bspc config click_to_focus any
bspc config pointer_action1 focus
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_action3 none

# behaviour

bspc config external_rules_command "$BSPWM_SCRIPTS_DIR"/adjust-new-window
bspc config removal_adjustment false
bspc rule -a Kupfer.py focus=on
bspc rule -a Pyroom state=floating
bspc rule -a dustmod.bin.x86_64 state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a jetbrains-idea state=tiled
bspc rule -a albert border=off focus=on

# set up desktops - need to do this after some settings above, since they're
# global and get applied to desktops when they're created/reset
"$BSPWM_SCRIPTS_DIR"/desktop-wall init
